baseurl: /starter
permalink: pretty
markdown: kramdown
paginate: 5
repo: starter
github_org: maptime
maptime:
  chapter: MaptimeTurku
  twitter: https://twitter.com/MaptimeTurku
  #disqus: YOUR DISQUS USERNAME
